### PR TITLE
Android issue 1372

### LINKED ISSUE #1372: [Android] The app crashes after tapping the push notifications
**Steps to reproduce:**
1. Log in to the site https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select the NIMH applet
3. Schedule events with notifications
4. Log in to the app as a user (ml2testbug@yandex.com// 123465)
5. Move the app to the background mode
6. Wait for the notifications
7. Open the notifications one by one
8. Look at the result
**Note:** This issue is reproduced randomly
**Actual results:** Sometimes the app crashes after tapping the push notifications. After tapping the first notification the app works but after tapping the second or the third the app crashes
**Video:** https://www.screencast.com/t/kChqTxCxImu1
**Expected result:** The app doesn't crash after tapping the push notification.
**Crash Log:**
`2020-12-04 10:31:07.019 4875-4875/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: lab.childmindinstitute.data, PID: 4875
    java.lang.RuntimeException: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{9c5af4d V.E...... ......ID 0,0-1440,2886}
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:344)
        at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:351)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{9c5af4d V.E...... ......ID 0,0-1440,2886}
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.<init>(RNGestureHandlerRootHelper.java:46)
        at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.initialize(RNGestureHandlerEnabledRootView.java:54)
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule$2.execute(RNGestureHandlerModule.java:605)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:498)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:846)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2020-12-04 10:31:39.088 12201-12201/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: lab.childmindinstitute.data, PID: 12201
    java.lang.RuntimeException: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{b1b5f96 V.E...... ......ID 0,0-1440,2886}
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:344)
        at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:351)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{b1b5f96 V.E...... ......ID 0,0-1440,2886}
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.<init>(RNGestureHandlerRootHelper.java:46)
        at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.initialize(RNGestureHandlerEnabledRootView.java:54)
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule$2.execute(RNGestureHandlerModule.java:605)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:498)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:846)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2020-12-04 11:21:28.954 12353-12353/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: lab.childmindinstitute.data, PID: 12353
    java.lang.RuntimeException: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{3296e0b V.E...... ......ID 0,0-1440,2886}
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:344)
        at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:351)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{3296e0b V.E...... ......ID 0,0-1440,2886}
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.<init>(RNGestureHandlerRootHelper.java:46)
        at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.initialize(RNGestureHandlerEnabledRootView.java:54)
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule$2.execute(RNGestureHandlerModule.java:605)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:498)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:846)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2020-12-04 11:21:45.865 14013-14013/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: lab.childmindinstitute.data, PID: 14013
    java.lang.RuntimeException: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{5061eaa V.E...... ......ID 0,0-1440,2886}
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:344)
        at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:351)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{5061eaa V.E...... ......ID 0,0-1440,2886}
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.<init>(RNGestureHandlerRootHelper.java:46)
        at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.initialize(RNGestureHandlerEnabledRootView.java:54)
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule$2.execute(RNGestureHandlerModule.java:605)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:498)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:846)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
`

**Environment:**
Staging
MindLogger app v 0.14.21
Pixel 4XL//Android 11
Samsung Galaxy S10 //Android 9

### PR DESCRIPTION
**Pull request by Matchdev120**
Resolved #1372 

Fixed the navigation issue on restart

### CODE REVIEW

File: app/scenes/AppLanguage/index.js [hunk 1]
```diff
@@ -39,6 +39,7 @@ class SettingsScreen extends React.Component {
     if (prevProps.appLanguage !== this.props.appLanguage) {
       Actions.splash();
       setTimeout(() => {
+        console.log('RESTART---------------------------------------111111111111111');
```
Comment (devbtech) [inline app/scenes/AppLanguage/index.js:42]: @Matchdev120 Please remove unnecessary console

**Review by devbtech — APPROVED** [review]
